version: '3'
services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - nest-app

  nest-app:
    build:
      context: ./nest-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  mongo:
    image: "mongo"
    ports:
      - "27017:27027"