name: Docker Compose Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push React App Docker image
      run: |
        cd react-app
        docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest

    - name: Build and push Nest App Docker image
      run: |
        cd nest-app
        docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/nest-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nest-app:latest

    - name: Docker Compose Up (Optional)
      run: |
        docker-compose up -d
