name: Docker Compose Build and Push

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Determine tag
      run: echo "DOCKER_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Build and push React App Docker image
      run: |
        TAG_SUFFIX=${DOCKER_TAG}
        if [ "$TAG_SUFFIX" == "main" ]; then
          TAG_SUFFIX="latest"
        fi
        cd react-app
        docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/react-app:$TAG_SUFFIX
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-app:$TAG_SUFFIX

    - name: Build and push Nest App Docker image
      run: |
        TAG_SUFFIX=${DOCKER_TAG}
        if [ "$TAG_SUFFIX" == "main" ]; then
          TAG_SUFFIX="latest"
        fi
        cd nest-app
        docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/nest-app:$TAG_SUFFIX
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nest-app:$TAG_SUFFIX

    # 이 부분은 GitHub Actions 러너에서 컨테이너를 실행합니다.
    # 필요하지 않다면 제거하거나 주석 처리해야 합니다.
    - name: Docker Compose Up (Optional)
      run: |
        docker-compose up -d